name: ANTLR

on:
  workflow_dispatch:
defaults:
  run:
    working-directory: antlr
jobs:
  pip-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install ANTLR
      run: ./install-on-ubuntu.sh via-pip
  apt-install:
    runs-on: ubuntu-latest
    steps:
    - name: Install ANTLR
      run: ./install-on-ubuntu.sh via-apt
   
